### ISSUE TITLE
"npm run dev" and "npm run build" leads to an error

### ISSUE THREAD

**Issue by Dmfama20** [kulmann/moodle-mod_philosophers#30]
Hello,
I tried to run the commands 
`npm run buid` and `npm run dev`
as explained in the readme. Unfortunately this ends with
`npm ERR! missing script: build` 
and 
`npm ERR! missing script: watch`

The corresponding logfiles are

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'watch' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose stack Error: missing script: watch
4 verbose stack     at run (/usr/share/npm/lib/run-script.js:155:19)
4 verbose stack     at /usr/share/npm/lib/run-script.js:63:5
4 verbose stack     at /usr/share/nodejs/read-package-json/read-json.js:116:5
4 verbose stack     at /usr/share/nodejs/read-package-json/read-json.js:436:5
4 verbose stack     at checkBinReferences_ (/usr/share/nodejs/read-package-json/read-json.js:391:45)
4 verbose stack     at final (/usr/share/nodejs/read-package-json/read-json.js:434:3)
4 verbose stack     at then (/usr/share/nodejs/read-package-json/read-json.js:161:5)
4 verbose stack     at /usr/share/nodejs/read-package-json/read-json.js:281:12
4 verbose stack     at /usr/share/nodejs/graceful-fs/graceful-fs.js:115:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
5 verbose cwd /var/www/html/moodle39/mod/philosophers/amd/build
6 verbose Linux 5.8.0-50-generic
7 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "watch"
8 verbose node v10.19.0
9 verbose npm  v6.14.4
10 error missing script: watch
11 verbose exit [ 1, true ]
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose stack Error: missing script: build
4 verbose stack     at run (/usr/share/npm/lib/run-script.js:155:19)
4 verbose stack     at /usr/share/npm/lib/run-script.js:63:5
4 verbose stack     at /usr/share/nodejs/read-package-json/read-json.js:116:5
4 verbose stack     at /usr/share/nodejs/read-package-json/read-json.js:436:5
4 verbose stack     at checkBinReferences_ (/usr/share/nodejs/read-package-json/read-json.js:391:45)
4 verbose stack     at final (/usr/share/nodejs/read-package-json/read-json.js:434:3)
4 verbose stack     at then (/usr/share/nodejs/read-package-json/read-json.js:161:5)
4 verbose stack     at /usr/share/nodejs/read-package-json/read-json.js:281:12
4 verbose stack     at /usr/share/nodejs/graceful-fs/graceful-fs.js:115:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
5 verbose cwd /var/www/html/moodle39/mod/philosophers/amd/build
6 verbose Linux 5.8.0-50-generic
7 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
8 verbose node v10.19.0
9 verbose npm  v6.14.4
10 error missing script: build
11 verbose exit [ 1, true ]

```

Any idea what is going wrong here? 

Thank you very much in advance!

Best,
Alex

**Comment by kulmann** [comment]
Hey, this project is not using `npm` but `yarn`. Vue related code lives in the `vue` subfolder, so you need to run `yarn install` once if you didn't before and then `yarn watch` for development. Did you do that? ;-)
